# -*- coding: utf-8 -*-
"""Ejercicio01

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1nU1vU1j_LSvma2-Pg6ydIJZGngnzMh1i

Exponente n más pequeño tal que (3 + 4j)**n tenga módulo mayor que 100
"""

modulo = abs(3+4j)
n=2
while modulo < 100:
  modulo = abs((3+4j)**n)
  n=n+1
exponente = n-1
print('Exponente n mas pequeño tal que |(3+4j)^n| > 100: ',exponente)
print('|(3+4j)^',exponente,'| = ',modulo)